import './globals.css'
import type { Metadata } from 'next'

import Header from "../../component/common/header"
import Popup from "../../component/common/popup"
import MainHeader from "../../component/common/main-header"
import Footer from "../../component/common/footer"
import { Titillium_Web } from 'next/font/google'

const titilliumWeb = Titillium_Web({ subsets: ['latin'],weight:['400','700','900','600'] })




export const metadata: Metadata = {
  title: 'Autodesk',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ `${titilliumWeb.className}`}>
         <Popup />
          <div className="flex">
            <Header/>
            <main className='w-mainContent relative'>
              <MainHeader />
              {children}
            <Footer />
            </main>
         </div>
      </body>
    </html>
  )
}
