import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from "../../component/common/header"
import Popup from "../../component/common/popup"
import MainHeader from "../../component/common/main-header"
import Footer from "../../component/common/footer"


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Autodesk',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`} >
         <Popup />
          <div className="flex">
            <Header/>
            <main className='w-mainContent relative'>
              <MainHeader />
              {children}
            <Footer />
            </main>
         </div>
      </body>
    </html>
  )
}
